name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Verificar sintaxe do Python
      run: python -m py_compile server.py

    - name: Disparar deploy no Render
      if: success()
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
